name: headless-ghost
region: nyc
static_sites:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: worldwidejamie/worldwidejamie
  name: worldwidejamie
  routes:
  - path: /
  source_dir: /
  output_dir: dist
envs:
  - key: CONTENT_API_KEY
    scope: RUN_TIME
    value: cfbb6084dbad5387129b82b80d
  - key: ADMIN_API_KEY
    scope: RUN_TIME
    value: SECRET